name: Easy_Structures
main: dkramer.WorldFeatures
version: 0.2
author: WorldSchematics
load: startup
description: Spawns .schematics into newly generated chunks.
website: https://github.com/robotnikthingy/WorldSchematics
commands:
permissions: